### ISSUE TITLE
NaN values

### ISSUE THREAD

**Issue by snashraf** [atgu/CHARR#4]
Hi team,

I was able to run the charr using hail version. 

```
charr_result = hl.compute_charr(mt, ref_AF=(1 - mt.info.AF[0]))
charr_result.export("charr_result.tsv")
print (charr_result)
```

I am getting values as NaN for most of sample ? How do we interpret this ? Do you have some suggestion for CHAR score to consider as contaminated ?

**Comment by snashraf** [comment]
Hi Team,

Do you have an update on this?

Regards,
Najeeb

**Comment by razmo63** [comment]
Hi, I got this error: 
Namespace(input_file_format='vcf', input_file_path='/Users/raziyehmohseni/Documents/Autumn_Semester_2024/research_training/Data/funkitten_rohann_vcfanno_filter_cadd_vep.vcf', output_dir='/Users/raziyehmohseni/Documents/Autumn_Semester_2024/research_training/charr/output', output_name='contamination_results', min_af=0.05, max_af=0.95, min_dp=20.0, max_dp=100.0, min_gq=20.0, ref_AF_field=None, data_type='genomes', extension='ht', n_partitions=1000, overwrite=True)
/Users/raziyehmohseni/Documents/CHARR/charr-env/lib/python3.12/site-packages/hail/context.py:352: UserWarning: Using hl.init with a default_reference argument is deprecated. To set a default reference genome after initializing hail, call `hl.default_reference` with an argument to set the default reference genome.
  warnings.warn(
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Running on Apache Spark version 3.5.2
SparkUI available at http://p199-n39.kthopen.kth.se:4041
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version 0.2.132-678e1f52b999
LOGGING: writing to /Users/raziyehmohseni/Documents/hail-20240920-1136-0.2.132-678e1f52b999.log
INFO (CHARR 102): Converting MatrixTable to VariantDataset...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/raziyehmohseni/Documents/CHARR/compute_charr.py", line 105, in <module>
    main(args)
  File "/Users/raziyehmohseni/Documents/CHARR/compute_charr.py", line 10, in main
    run_charr(
  File "/Users/raziyehmohseni/Documents/CHARR/utils.py", line 202, in run_charr
    mt = compute_charr(mtds, min_af, max_af, min_dp, max_dp, min_gq, ref_AF_field, data_type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/raziyehmohseni/Documents/CHARR/utils.py", line 103, in compute_charr
    mtds = mtds.select_entries("END", "LA", "LGT", "GQ", "DP", "LAD")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/raziyehmohseni/Documents/CHARR/charr-env/lib/python3.12/site-packages/hail/matrixtable.py", line 1435, in select_entries
    new_entry = get_select_exprs(caller, exprs, named_exprs, self._entry_indices, self._entry)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/raziyehmohseni/Documents/CHARR/charr-env/lib/python3.12/site-packages/hail/utils/misc.py", line 468, in get_select_exprs
    exprs = [indices.source[e] if isinstance(e, str) else e for e in exprs]
             ~~~~~~~~~~~~~~^^^
  File "/Users/raziyehmohseni/Documents/CHARR/charr-env/lib/python3.12/site-packages/hail/matrixtable.py", line 813, in __getitem__
    return self._get_field(item)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/raziyehmohseni/Documents/CHARR/charr-env/lib/python3.12/site-packages/hail/table.py", line 153, in _get_field
    raise LookupError(get_nice_field_error(self, item))
LookupError: MatrixTable instance has no field 'END'
    Hint: use 'describe()' to show the names of all data fields.
CHARR run failed. Please check for errors.
